Expunge COFFEE
firedrakeproject/tsfc pull request #291
Opened 2023-05-01 13:07 UTC by connorjward

Depends on https://github.com/inducer/loopy/issues/762

2023-05-03 12:36 UTC, JDBetteridge requested changes

2023-05-03 12:36 UTC, JDBetteridge commented on tsfc/driver.py
> +        import tsfc.kernel_interface.firedrake_loopy as firedrake_interface_loopy
Move to top

2023-05-03 12:36 UTC, JDBetteridge commented on tsfc/kernel_interface/firedrake_loopy.py
>          """
Add return type to docstring

2023-05-03 12:36 UTC, JDBetteridge commented on tsfc/loopy.py
> +             return_increments=True, log=False, stop_early=False):
Remove `stop_early`

2023-05-03 15:36 UTC, connorjward commented on tests/test_tensor.py
> +    # FIXME This is failing without this change because the value is 3.16
Start at a higher degree instead.

2023-05-10 14:30 UTC, JDBetteridge approved these changes

2023-05-10 14:31 UTC, merged