Default to spectral variant on simplices
firedrakeproject/tsfc pull request #301
Opened 2023-10-14 21:15 UTC by pbrubeck

Depends on https://github.com/firedrakeproject/fiat/pull/46

2023-11-15 13:42 UTC, JDBetteridge requested changes
Can you open a draft PR on firedrake with the do not merge label, which tests this branch, please. Also resolve the conflicts.

2023-11-15 13:48 UTC, pbrubeck commented on tests/test_create_fiat_element.py
> +    ufl_element = ufl.FiniteElement('DP', ufl.triangle, 2, variant='spectral')
```suggestion
    ufl_element = finat.ufl.FiniteElement('DP', ufl.triangle, 2, variant='spectral')
```

2023-11-15 13:49 UTC, pbrubeck commented on tests/test_create_finat_element.py
> +    ufl_element = ufl.FiniteElement('DP', ufl.triangle, 2, variant='spectral')
```suggestion
    ufl_element = finat.ufl.FiniteElement('DP', ufl.triangle, 2, variant='spectral')
```

2023-11-15 13:49 UTC, pbrubeck commented on tests/test_create_finat_element.py
> +    ufl_element = ufl.FiniteElement('DP L2', ufl.triangle, 2, variant='spectral')
```suggestion
    ufl_element = finat.ufl.FiniteElement('DP L2', ufl.triangle, 2, variant='spectral')
```

2023-11-17 09:56 UTC, connorjward approved these changes
This is passing Firedrake tests [here](https://github.com/firedrakeproject/firedrake/pull/3193). In future @pbrubeck please link between that PR and this one so it can be found.

2023-11-17 09:56 UTC, merged