Update UFL element interface: move elements to FInAT
firedrakeproject/tsfc pull request #302
Opened 2023-10-16 16:23 UTC by mscroggs

This is an extension of https://github.com/firedrakeproject/tsfc/pull/300.

In https://github.com/FInAT/FInAT/pull/111, I moved the elements from `ufl.legacy` to `finat.ufl`. This PR updates tsfc to use the elements from there.

This is all a consequence of https://github.com/FEniCS/ufl/pull/197.

This PR is coupled with https://github.com/firedrakeproject/firedrake/pull/3166, https://github.com/FInAT/FInAT/pull/111, and https://github.com/NGSolve/ngsPETSc/pull/7.

2023-11-08 16:20 UTC, dham reviewed
fix the imports and this is good to go.

2023-11-08 16:20 UTC, dham commented on requirements-git.txt
> +git+https://github.com/FEniCS/ufl.git
This seems wrong.

2023-11-08 16:57 UTC, mscroggs commented on requirements-git.txt
> +git+https://github.com/FInAT/FInAT.git@mscroggs/ufl-elements
This branch name will need removing once all the branches are merged

2023-11-15 09:50 UTC, connorjward submitted a review, later dismissed
This is good.

2023-11-15 13:25 UTC, JDBetteridge requested changes
Don't worry about adding these I'll add the suggestions to a batch once I've checked the other branches 🙂

2023-11-15 13:25 UTC, JDBetteridge commented on requirements-git.txt
> +git+https://github.com/firedrakeproject/ufl.git@dolci/merge_upstream_2
```suggestion
git+https://github.com/firedrakeproject/ufl.git#egg=fenics-ufl
```

2023-11-15 13:25 UTC, JDBetteridge commented on requirements-git.txt
> +git+https://github.com/FInAT/FInAT.git@mscroggs/ufl-elements
```suggestion
git+https://github.com/FInAT/FInAT.git#egg=finat
```

2023-11-15 13:30 UTC, JDBetteridge approved these changes

2023-11-15 13:34 UTC, merged