Ksagiyam/attach dtype to nodes
firedrakeproject/tsfc pull request #327
Opened 2024-11-07 23:40 UTC by ksagiyam

2024-11-13 16:12 UTC, dham requested changes
just fix the "!=" to "is not" for types.

2024-11-13 16:12 UTC, dham commented on gem/gem.py
> +        if dtype != uint_type:
```suggestion
        if dtype is not uint_type:
```

2024-11-19 14:38 UTC, ksagiyam commented
It turned out that object equal caused some pickling tests to fail:
```
import numpy as np 
import pickle 


obj1 = np.dtype(int) 
obj2 = np.dtype(int) 
print(obj1 == obj2)  # True 
print(obj1 is obj2)  # True 
obj1_pickled = pickle.dumps(obj1) 
obj1_loaded = pickle.loads(obj1_pickled) 
print(obj1_loaded == obj1)  # True 
print(obj1_loaded is obj1)  # False 
```
So probably we should just use `==` instead of object equal.

2024-11-20 17:07 UTC, dham approved these changes

2024-11-20 17:08 UTC, merged